export const STARTUP_DEFERRED_RUNTIME_MS = 900;
export const STARTUP_DEFERRED_IMPORT_MS = 1200;
export const STARTUP_DEFERRED_SEARCH_DEPENDENCY_MS = 1600;
export const STARTUP_BACKGROUND_COMPLETE_MS = 2000;
